version: '2.1'
services:
  app:
    build: .
    command: npm run start
    environment:
      - PORT=8080
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=bilue
    ports:
      - "8080:8080"
      - "5858:5858"
    links:
      - mysql
    volumes:
      - .:/app/
    network_mode: bridge
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=bilue
      - MYSQL_ROOT_PASSWORD=bilue
    ports:
      - "3306:3306"
    network_mode: bridge